# Generated by Django 2.1.4 on 2018-12-05 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_client'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Usuario',
        ),
    ]
