# Generated by Django 2.1.4 on 2018-12-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181205_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='foto',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='foto',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
